# Generated by Django 2.2.1 on 2019-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='SubCollege',
            field=models.ManyToManyField(to='appone.College'),
        ),
    ]
